[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.deadnix]
command = "deadnix"
options = ["--edit"]
includes = ["*.nix"]

[formatter.stylua]
command = "stylua"
includes = ["*.lua"]

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
